name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - *


jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ macos-10.15, macos-11.0 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install HomeBrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install dependencies
        run: brew install fftw portaudio

      - name: Build
        run: make -f build.mk
